### ISSUE TITLE
Doesn’t work for `/* GraphQL */` commented template strings

### ISSUE THREAD

**Issue by jaydenseric** [0no-co/GraphQLSP#122]
Template strings containing GraphQL queries that have a leading comment `/* GraphQL */` do not have any sort of IntelliSense you would expect this plugin to provide. If you replace the comment with a `qgl` template string tag function, the IntelliSense starts working. The GraphQL client we're using, [`graphql-react`](https://github.com/jaydenseric/graphql-react), (like several other GraphQL clients) doesn't use template string tag functions for GraphQL; it just uses a string for the query.

**Comment by JoviDeCroock** [comment]
These fall into the court of a `NoSubstituationTemplateLiteral` so since the addition of the new GraphQL-Code-Generator we do have a good path forward to supporting this case 🙌 we would need to alter that [here](https://github.com/0no-co/GraphQLSP/blob/main/packages/graphqlsp/src/ast/index.ts#L34).

Just so I cover all bases, how does fragment interpolation and other ways to co-locate data-requirements look here?

**Comment by jaydenseric** [comment]
Fragment template strings also have a leading comment `/* GraphQL */`, and any query in a template string that references a fragment interpolates the imported fragment template string at the start.

**Comment by JoviDeCroock** [comment]
On second thought, type-generation won't work as those are just strings and aren't cast to a `DocumentNode`

**Comment by JoviDeCroock** [comment]
TypeScript does not support comments in the LSP so I'll lean into not supporting this alltogether
