### ISSUE TITLE
Fragment autocomplete doesn't work until prettier formats the string properly

### ISSUE THREAD

**Issue by nandorojo** [0no-co/GraphQLSP#130]
Small thing:

<img width="762" alt="image" src="https://github.com/0no-co/GraphQLSP/assets/13172299/aa13a465-4d02-498d-93ec-6e5144d8239c">

^ Those aren't fields on `Venue`.

This should give me `Venue` fields, but it doesn't until I add a field, save, and it formats the spacing.

Now, once it's spaced properly, it does give me venue fields:

<img width="538" alt="Screenshot 2023-12-08 at 10 02 17 AM" src="https://github.com/0no-co/GraphQLSP/assets/13172299/b914eb55-9902-4093-a88a-a453d0b32a37">

**Comment by JoviDeCroock** [comment]
This is a similar issue to #127 it basically needs to find the spacing 😅 
<img width="536" alt="Screenshot 2023-12-09 at 08 25 23" src="https://github.com/0no-co/GraphQLSP/assets/17125876/3a8f160f-a588-4adb-b475-984e5e8c56f2"> i.e. it works here because there is a space after... Not entirely sure yet how to solve this but basically else it tries to fuse the suggestions with `}`.
