### ISSUE TITLE
Autocomplete should not show fields that we are already using

### ISSUE THREAD

**Issue by JoviDeCroock** [0no-co/GraphQLSP#16]
When we are using the auto-complete we should not display `id` when it's already used, neither should we propose a fragment-spread when it has already been spread.

**Comment by TheMightyPenguin** [comment]
I can take this one!

**Comment by JoviDeCroock** [comment]
Assigned it to you so folks have visibility into it, thank you!

**Comment by TheMightyPenguin** [comment]
@JoviDeCroock After some debugging, I think this functionality should actually be built it into the `graphql-language-service` package. The TS language server already handles this and only provides unused fields in their recommendations.

Gonna hack on `graphql-language-service` to get a PR over to the graphiql repo with that, otherwise the other alternative is to vendor/modify those functions in this repo!

**Comment by JoviDeCroock** [comment]
Currently it looks like GraphiQL does not take in account the surrounding fields neither does the function hint at doing so 😅 it mostly seems to take the context of the current typed token in account (or the absence thereof). We might need to filter it ourselves based on the selection-set we are on, or maybe the LSP is smart enough to de-duplicate based on some insertText/... would need to look into that.

**Comment by TheMightyPenguin** [comment]
@JoviDeCroock opened a PR with a fix for this!
